kumuluzee:
  name: itemSpecific
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  datasources:
    - jndi-name: jdbc/ItemSpecificDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/itemSpecific
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
rest-properties:
  external-services:
    product-service:
      enabled: true
